version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: postgres-db2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: bookstore-api
    restart: unless-stopped
    environment:
      PORT: 3000
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bookstore
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
